[workspace]
members = [
    "packages/*"
]

[workspace.dependencies]
cairo_test = "2.16.0"

[cairo]
enable-gas = false

[workspace.package]
description = "Reusable Cairo circuits for building zero-knowledge protocols and applications"
repository = "https://github.com/zk-kit/zk-kit.cairo"
documentation = "https://github.com/zk-kit/zk-kit.cairo#readme"
homepage = "https://github.com/zk-kit/zk-kit.cairo"
license = "MIT"
cairo-version = "2.15.0"
scarb-version = "2.15.2"
keywords = [
    "zero-knowledge"
]