[package]
name = "zk_kit_binary_merkle_root"
version = "0.1.0"
edition = "2025_12"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[cairo]
enable-gas = false

[dependencies]

[dev-dependencies]
cairo_test = "2.16.0"
